import Head from 'next/head';
import MainLayout from '../components/layouts/MainLayout';
import Hero1 from '../components/Hero/Hero1/Hero1';
import Collection1 from '../components/Collections/Collection1/Collection1';

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero1 />
      <Collection1 />
    </MainLayout>
  );
}
